package generate

import (
	"fmt"
	"path/filepath"
	"strings"
	"tools/please_wit/ast"
)

// CppGenerator generates C++ headers and companion source files from WIT AST.
type CppGenerator struct{}

func (g *CppGenerator) Name() string {
	return "cpp"
}

func (g *CppGenerator) mapPrimitiveType(name string) string {
	switch name {
	case "s8":
		return "int8_t"
	case "s16":
		return "int16_t"
	case "s32":
		return "int32_t"
	case "s64":
		return "int64_t"
	case "u8":
		return "uint8_t"
	case "u16":
		return "uint16_t"
	case "u32":
		return "uint32_t"
	case "u64":
		return "uint64_t"
	case "f32":
		return "float"
	case "f64":
		return "double"
	case "bool":
		return "bool"
	case "string":
		return "std::string"
	case "char":
		return "char32_t"
	case "unit", "_":
		return "void"
	}
	return ToPascalCase(name)
}

// MapWitType converts an AST TypeRef into its idiomatic C++ representation.
func (g *CppGenerator) MapWitType(t *ast.TypeRef) string {
	if t == nil {
		return "void"
	}

	switch t.Kind {
	case ast.KindPrimitive:
		return g.mapPrimitiveType(t.Name)

	case ast.KindList:
		inner := "void"
		if len(t.TypeArgs) > 0 {
			inner = g.MapWitType(t.TypeArgs[0])
		}
		return fmt.Sprintf("std::vector<%s>", inner)

	case ast.KindOption:
		inner := "void"
		if len(t.TypeArgs) > 0 {
			inner = g.MapWitType(t.TypeArgs[0])
		}
		return fmt.Sprintf("std::optional<%s>", inner)

	case ast.KindResult:
		if len(t.TypeArgs) > 0 {
			okType := g.MapWitType(t.TypeArgs[0])
			if okType == "void" {
				return "bool"
			}
			return fmt.Sprintf("std::optional<%s>", okType)
		}
		return "bool"

	case ast.KindTuple:
		var parts []string
		for _, arg := range t.TypeArgs {
			parts = append(parts, g.MapWitType(arg))
		}
		return fmt.Sprintf("std::tuple<%s>", strings.Join(parts, ", "))

	case ast.KindNamed:
		return ToPascalCase(t.Name)
	}

	return "void"
}

func (g *CppGenerator) Generate(pkg *ast.Package, opts Options, baseName string) ([]OutputFile, error) {
	filename := opts.CompanionFilename
	if filename == "" {
		if baseName != "" {
			filename = ToSnakeCase(baseName) + ".h"
		} else {
			filename = "bindings.h"
		}
	}

	hContent := g.generateCppCode(pkg, opts.Package)
	cppFilename := strings.TrimSuffix(filename, filepath.Ext(filename)) + ".cpp"
	cppContent := fmt.Sprintf("// Auto-generated by please_wit from WIT AST. DO NOT EDIT.\n#include \"%s\"\n", filename)

	return []OutputFile{
		{Name: filename, Content: hContent},
		{Name: cppFilename, Content: cppContent},
	}, nil
}

func (g *CppGenerator) createNamespace(targetPackage string, pkg *ast.Package) string {
	ns := targetPackage
	if ns == "" {
		if pkg.Namespace != "" && pkg.Name != "" {
			ns = fmt.Sprintf("%s_%s", pkg.Namespace, pkg.Name)
		} else if pkg.Name != "" {
			ns = pkg.Name
		} else {
			ns = "wit"
		}
	}
	ns = strings.ToLower(strings.ReplaceAll(strings.ReplaceAll(ns, ":", "_"), "-", "_"))
	return ns
}

func (g *CppGenerator) processRecords(sb *strings.Builder, records []ast.Record) {
	for _, rec := range records {
		sb.WriteString(fmt.Sprintf("struct %s {\n", ToPascalCase(rec.Name)))
		for _, f := range rec.Fields {
			sb.WriteString(fmt.Sprintf("    %s %s;\n", g.MapWitType(f.Type), ToSnakeCase(f.Name)))
		}
		sb.WriteString("};\n\n")
	}
}

func (g *CppGenerator) processEnums(sb *strings.Builder, enums []ast.Enum) {
	for _, enm := range enums {
		sb.WriteString(fmt.Sprintf("enum class %s {\n", ToPascalCase(enm.Name)))
		for _, c := range enm.Cases {
			sb.WriteString(fmt.Sprintf("    %s,\n", ToPascalCase(c.Name)))
		}
		sb.WriteString("};\n\n")
	}
}

func (g *CppGenerator) processTypeAliases(sb *strings.Builder, typeDefs []ast.TypeDef) {
	for _, tdef := range typeDefs {
		sb.WriteString(fmt.Sprintf("using %s = %s;\n\n", ToPascalCase(tdef.Name), g.MapWitType(tdef.Type)))
	}
}

func (g *CppGenerator) processInterface(sb *strings.Builder, iface ast.Interface) {
	sb.WriteString(fmt.Sprintf("class %s {\npublic:\n    virtual ~%s() = default;\n", ToPascalCase(iface.Name), ToPascalCase(iface.Name)))
	for _, fn := range iface.Functions {
		var params []string
		for _, p := range fn.Params {
			t := g.MapWitType(p.Type)
			if strings.HasPrefix(t, "std::") {
				params = append(params, fmt.Sprintf("const %s& %s", t, ToSnakeCase(p.Name)))
			} else {
				params = append(params, fmt.Sprintf("%s %s", t, ToSnakeCase(p.Name)))
			}
		}
		retType := g.MapWitType(fn.Results)
		sb.WriteString(fmt.Sprintf("    virtual %s %s(%s) = 0;\n", retType, ToCamelCase(fn.Name), strings.Join(params, ", ")))
	}
	sb.WriteString("};\n\n")
}

func (g *CppGenerator) processResources(sb *strings.Builder, resources []ast.Resource) {
	for _, res := range resources {
		sb.WriteString(fmt.Sprintf("class %s {\npublic:\n    virtual ~%s() = default;\n", ToPascalCase(res.Name), ToPascalCase(res.Name)))
		for _, fn := range res.Methods {
			var params []string
			for _, p := range fn.Params {
				t := g.MapWitType(p.Type)
				if strings.HasPrefix(t, "std::") {
					params = append(params, fmt.Sprintf("const %s& %s", t, ToSnakeCase(p.Name)))
				} else {
					params = append(params, fmt.Sprintf("%s %s", t, ToSnakeCase(p.Name)))
				}
			}
			retType := g.MapWitType(fn.Results)
			sb.WriteString(fmt.Sprintf("    virtual %s %s(%s) = 0;\n", retType, ToCamelCase(fn.Name), strings.Join(params, ", ")))
		}
		sb.WriteString("};\n\n")
	}
}

func (g *CppGenerator) generateCppCode(pkg *ast.Package, targetPackage string) string {
	var sb strings.Builder
	sb.WriteString("// Auto-generated by please_wit from WIT AST. DO NOT EDIT.\n")
	sb.WriteString("#pragma once\n\n")
	sb.WriteString("#include <cstdint>\n")
	sb.WriteString("#include <string>\n")
	sb.WriteString("#include <vector>\n")
	sb.WriteString("#include <optional>\n")
	sb.WriteString("#include <tuple>\n\n")

	ns := g.createNamespace(targetPackage, pkg)

	sb.WriteString(fmt.Sprintf("namespace %s {\n\n", ns))

	for _, iface := range pkg.Interfaces {
		// 1. Records
		g.processRecords(&sb, iface.Records)

		// 2. Enums
		g.processEnums(&sb, iface.Enums)

		// 3. Type aliases
		g.processTypeAliases(&sb, iface.TypeDefs)

		// 4. Resources
		g.processResources(&sb, iface.Resources)

		// 5. Interface class
		hasResourceWithSameName := false
		for _, res := range iface.Resources {
			if ToPascalCase(res.Name) == ToPascalCase(iface.Name) {
				hasResourceWithSameName = true
				break
			}
		}

		if !hasResourceWithSameName || len(iface.Functions) > 0 {
			g.processInterface(&sb, iface)
		}
	}

	sb.WriteString(fmt.Sprintf("} // namespace %s\n", ns))
	return sb.String()
}
