package generate

import (
	"fmt"
	"strings"
	"tools/please_wit/ast"
)

// MapWitTypeToCpp converts an AST TypeRef into its idiomatic C++ representation.
func MapWitTypeToCpp(t *ast.TypeRef) string {
	if t == nil {
		return "void"
	}

	switch t.Kind {
	case ast.KindPrimitive:
		switch t.Name {
		case "s8":
			return "int8_t"
		case "s16":
			return "int16_t"
		case "s32":
			return "int32_t"
		case "s64":
			return "int64_t"
		case "u8":
			return "uint8_t"
		case "u16":
			return "uint16_t"
		case "u32":
			return "uint32_t"
		case "u64":
			return "uint64_t"
		case "f32":
			return "float"
		case "f64":
			return "double"
		case "bool":
			return "bool"
		case "string":
			return "std::string"
		case "char":
			return "char32_t"
		case "unit", "_":
			return "void"
		}
		return ToPascalCase(t.Name)

	case ast.KindList:
		inner := "void"
		if len(t.TypeArgs) > 0 {
			inner = MapWitTypeToCpp(t.TypeArgs[0])
		}
		return fmt.Sprintf("std::vector<%s>", inner)

	case ast.KindOption:
		inner := "void"
		if len(t.TypeArgs) > 0 {
			inner = MapWitTypeToCpp(t.TypeArgs[0])
		}
		return fmt.Sprintf("std::optional<%s>", inner)

	case ast.KindResult:
		if len(t.TypeArgs) > 0 {
			okType := MapWitTypeToCpp(t.TypeArgs[0])
			if okType == "void" {
				return "bool"
			}
			return fmt.Sprintf("std::optional<%s>", okType)
		}
		return "bool"

	case ast.KindTuple:
		var parts []string
		for _, arg := range t.TypeArgs {
			parts = append(parts, MapWitTypeToCpp(arg))
		}
		return fmt.Sprintf("std::tuple<%s>", strings.Join(parts, ", "))

	case ast.KindNamed:
		return ToPascalCase(t.Name)
	}

	return "void"
}

// GenerateCppCode emits C++ headers from a WIT package AST.
func GenerateCppCode(pkg *ast.Package, targetPackage string) string {
	var sb strings.Builder
	sb.WriteString("// Auto-generated by please_wit from WIT AST. DO NOT EDIT.\n")
	sb.WriteString("#pragma once\n\n")
	sb.WriteString("#include <cstdint>\n")
	sb.WriteString("#include <string>\n")
	sb.WriteString("#include <vector>\n")
	sb.WriteString("#include <optional>\n")
	sb.WriteString("#include <tuple>\n\n")

	ns := targetPackage
	if ns == "" {
		if pkg.Namespace != "" && pkg.Name != "" {
			ns = fmt.Sprintf("%s_%s", pkg.Namespace, pkg.Name)
		} else if pkg.Name != "" {
			ns = pkg.Name
		} else {
			ns = "wit"
		}
	}
	ns = strings.ToLower(strings.ReplaceAll(strings.ReplaceAll(ns, ":", "_"), "-", "_"))

	sb.WriteString(fmt.Sprintf("namespace %s {\n\n", ns))

	for _, iface := range pkg.Interfaces {
		// 1. Records
		for _, rec := range iface.Records {
			sb.WriteString(fmt.Sprintf("struct %s {\n", ToPascalCase(rec.Name)))
			for _, f := range rec.Fields {
				sb.WriteString(fmt.Sprintf("    %s %s;\n", MapWitTypeToCpp(f.Type), ToSnakeCase(f.Name)))
			}
			sb.WriteString("};\n\n")
		}

		// 2. Enums
		for _, enm := range iface.Enums {
			sb.WriteString(fmt.Sprintf("enum class %s {\n", ToPascalCase(enm.Name)))
			for _, c := range enm.Cases {
				sb.WriteString(fmt.Sprintf("    %s,\n", ToPascalCase(c.Name)))
			}
			sb.WriteString("};\n\n")
		}

		// 3. Type aliases
		for _, tdef := range iface.TypeDefs {
			sb.WriteString(fmt.Sprintf("using %s = %s;\n\n", ToPascalCase(tdef.Name), MapWitTypeToCpp(tdef.Type)))
		}

		// 4. Interface class
		sb.WriteString(fmt.Sprintf("class %s {\npublic:\n    virtual ~%s() = default;\n", ToPascalCase(iface.Name), ToPascalCase(iface.Name)))
		for _, fn := range iface.Functions {
			var params []string
			for _, p := range fn.Params {
				t := MapWitTypeToCpp(p.Type)
				if strings.HasPrefix(t, "std::") {
					params = append(params, fmt.Sprintf("const %s& %s", t, ToSnakeCase(p.Name)))
				} else {
					params = append(params, fmt.Sprintf("%s %s", t, ToSnakeCase(p.Name)))
				}
			}
			retType := MapWitTypeToCpp(fn.Results)
			sb.WriteString(fmt.Sprintf("    virtual %s %s(%s) = 0;\n", retType, ToCamelCase(fn.Name), strings.Join(params, ", ")))
		}
		sb.WriteString("};\n\n")
	}

	sb.WriteString(fmt.Sprintf("} // namespace %s\n", ns))
	return sb.String()
}
