package generate

import (
	"fmt"
	"strings"
	"tools/please_wit/ast"
)

// GoGenerator generates Go interfaces, structs, and enums from WIT AST.
type GoGenerator struct{}

func (g *GoGenerator) Name() string {
	return "go"
}

func (g *GoGenerator) mapPrimitiveType(name string) string {
	switch name {
	case "s8":
		return "int8"
	case "s16":
		return "int16"
	case "s32":
		return "int32"
	case "s64":
		return "int64"
	case "u8":
		return "uint8"
	case "u16":
		return "uint16"
	case "u32":
		return "uint32"
	case "u64":
		return "uint64"
	case "f32":
		return "float32"
	case "f64":
		return "float64"
	case "bool":
		return "bool"
	case "string":
		return "string"
	case "char":
		return "rune"
	case "unit", "_":
		return ""
	}
	return ToPascalCase(name)
}

// MapWitType converts an AST TypeRef into its idiomatic Go representation.
func (g *GoGenerator) MapWitType(t *ast.TypeRef) string {
	if t == nil {
		return ""
	}

	switch t.Kind {
	case ast.KindPrimitive:
		return g.mapPrimitiveType(t.Name)

	case ast.KindList:
		inner := "any"
		if len(t.TypeArgs) > 0 {
			inner = g.MapWitType(t.TypeArgs[0])
		}
		return fmt.Sprintf("[]%s", inner)

	case ast.KindOption:
		inner := "any"
		if len(t.TypeArgs) > 0 {
			inner = g.MapWitType(t.TypeArgs[0])
		}
		return fmt.Sprintf("*%s", inner)

	case ast.KindResult:
		if len(t.TypeArgs) > 0 {
			okType := g.MapWitType(t.TypeArgs[0])
			if okType == "" {
				return "error"
			}
			return fmt.Sprintf("(%s, error)", okType)
		}
		return "error"

	case ast.KindTuple:
		var parts []string
		for _, arg := range t.TypeArgs {
			parts = append(parts, g.MapWitType(arg))
		}
		return fmt.Sprintf("struct{%s}", strings.Join(parts, "; "))

	case ast.KindNamed:
		return ToPascalCase(t.Name)
	}

	return "any"
}

func (g *GoGenerator) Generate(pkg *ast.Package, opts Options, baseName string) ([]OutputFile, error) {
	filename := opts.CompanionFilename
	if filename == "" {
		if baseName != "" {
			filename = ToSnakeCase(baseName) + ".go"
		} else {
			filename = "bindings.go"
		}
	}

	content := g.generateGoCode(pkg, opts.Package)
	return []OutputFile{{Name: filename, Content: content}}, nil
}

func (g *GoGenerator) resolvePackage(pkg *ast.Package, targetPackage string) string {
	resolvedPkg := targetPackage
	if resolvedPkg == "" {
		if pkg.Name != "" {
			resolvedPkg = pkg.Name
		} else if pkg.Namespace != "" {
			resolvedPkg = pkg.Namespace
		} else {
			resolvedPkg = "wit"
		}
	}
	if idx := strings.LastIndex(resolvedPkg, ":"); idx != -1 {
		resolvedPkg = resolvedPkg[idx+1:]
	}
	resolvedPkg = strings.ToLower(strings.ReplaceAll(resolvedPkg, "-", "_"))
	return resolvedPkg
}

func (g *GoGenerator) processRecords(sb *strings.Builder, records []ast.Record) {
	for _, rec := range records {
		sb.WriteString(fmt.Sprintf("type %s struct {\n", ToPascalCase(rec.Name)))
		for _, f := range rec.Fields {
			sb.WriteString(fmt.Sprintf("\t%s %s\n", ToPascalCase(f.Name), g.MapWitType(f.Type)))
		}
		sb.WriteString("}\n\n")
	}
}

func (g *GoGenerator) processEnums(sb *strings.Builder, enums []ast.Enum) {
	for _, enm := range enums {
		enmName := ToPascalCase(enm.Name)
		sb.WriteString(fmt.Sprintf("type %s int\n\nconst (\n", enmName))
		for i, c := range enm.Cases {
			if i == 0 {
				sb.WriteString(fmt.Sprintf("\t%s_%s %s = iota\n", enmName, ToPascalCase(c.Name), enmName))
			} else {
				sb.WriteString(fmt.Sprintf("\t%s_%s\n", enmName, ToPascalCase(c.Name)))
			}
		}
		sb.WriteString(")\n\n")
	}
}

func (g *GoGenerator) processTypeAliases(sb *strings.Builder, typeDefs []ast.TypeDef) {
	for _, tdef := range typeDefs {
		sb.WriteString(fmt.Sprintf("type %s = %s\n\n", ToPascalCase(tdef.Name), g.MapWitType(tdef.Type)))
	}
}

func (g *GoGenerator) processInterface(sb *strings.Builder, iface ast.Interface) {
	sb.WriteString(fmt.Sprintf("type %s interface {\n", ToPascalCase(iface.Name)))
	for _, fn := range iface.Functions {
		var params []string
		for _, p := range fn.Params {
			params = append(params, fmt.Sprintf("%s %s", ToCamelCase(p.Name), g.MapWitType(p.Type)))
		}
		retType := g.MapWitType(fn.Results)
		retClause := ""
		if retType != "" {
			retClause = " " + retType
		}
		sb.WriteString(fmt.Sprintf("\t%s(%s)%s\n", ToPascalCase(fn.Name), strings.Join(params, ", "), retClause))
	}
	sb.WriteString("}\n\n")
}

func (g *GoGenerator) generateGoCode(pkg *ast.Package, targetPackage string) string {
	var sb strings.Builder
	sb.WriteString("// Code generated by please_wit from WIT AST. DO NOT EDIT.\n")

	resolvedPkg := g.resolvePackage(pkg, targetPackage)

	sb.WriteString(fmt.Sprintf("package %s\n\n", resolvedPkg))

	for _, iface := range pkg.Interfaces {
		// 1. Records
		g.processRecords(&sb, iface.Records)

		// 2. Enums
		g.processEnums(&sb, iface.Enums)

		// 3. Type aliases
		g.processTypeAliases(&sb, iface.TypeDefs)

		// 4. Interface declaration
		g.processInterface(&sb, iface)
	}

	return sb.String()
}
