package generate

import (
	"fmt"
	"strings"
	"tools/please_wit/ast"
)

// MapWitTypeToGo converts an AST TypeRef into its idiomatic Go representation.
func MapWitTypeToGo(t *ast.TypeRef) string {
	if t == nil {
		return ""
	}

	switch t.Kind {
	case ast.KindPrimitive:
		switch t.Name {
		case "s8":
			return "int8"
		case "s16":
			return "int16"
		case "s32":
			return "int32"
		case "s64":
			return "int64"
		case "u8":
			return "uint8"
		case "u16":
			return "uint16"
		case "u32":
			return "uint32"
		case "u64":
			return "uint64"
		case "f32":
			return "float32"
		case "f64":
			return "float64"
		case "bool":
			return "bool"
		case "string":
			return "string"
		case "char":
			return "rune"
		case "unit", "_":
			return ""
		}
		return ToPascalCase(t.Name)

	case ast.KindList:
		inner := "any"
		if len(t.TypeArgs) > 0 {
			inner = MapWitTypeToGo(t.TypeArgs[0])
		}
		return fmt.Sprintf("[]%s", inner)

	case ast.KindOption:
		inner := "any"
		if len(t.TypeArgs) > 0 {
			inner = MapWitTypeToGo(t.TypeArgs[0])
		}
		return fmt.Sprintf("*%s", inner)

	case ast.KindResult:
		if len(t.TypeArgs) > 0 {
			okType := MapWitTypeToGo(t.TypeArgs[0])
			if okType == "" {
				return "error"
			}
			return fmt.Sprintf("(%s, error)", okType)
		}
		return "error"

	case ast.KindTuple:
		var parts []string
		for _, arg := range t.TypeArgs {
			parts = append(parts, MapWitTypeToGo(arg))
		}
		return fmt.Sprintf("struct{%s}", strings.Join(parts, "; "))

	case ast.KindNamed:
		return ToPascalCase(t.Name)
	}

	return "any"
}

// GenerateGoCode emits Go interfaces and structs from a WIT package AST.
func GenerateGoCode(pkg *ast.Package, targetPackage string) string {
	var sb strings.Builder
	sb.WriteString("// Code generated by please_wit from WIT AST. DO NOT EDIT.\n")

	resolvedPkg := targetPackage
	if resolvedPkg == "" {
		if pkg.Name != "" {
			resolvedPkg = pkg.Name
		} else if pkg.Namespace != "" {
			resolvedPkg = pkg.Namespace
		} else {
			resolvedPkg = "wit"
		}
	}
	if idx := strings.LastIndex(resolvedPkg, ":"); idx != -1 {
		resolvedPkg = resolvedPkg[idx+1:]
	}
	resolvedPkg = strings.ToLower(strings.ReplaceAll(resolvedPkg, "-", "_"))

	sb.WriteString(fmt.Sprintf("package %s\n\n", resolvedPkg))

	for _, iface := range pkg.Interfaces {
		// 1. Records
		for _, rec := range iface.Records {
			sb.WriteString(fmt.Sprintf("type %s struct {\n", ToPascalCase(rec.Name)))
			for _, f := range rec.Fields {
				sb.WriteString(fmt.Sprintf("\t%s %s\n", ToPascalCase(f.Name), MapWitTypeToGo(f.Type)))
			}
			sb.WriteString("}\n\n")
		}

		// 2. Enums
		for _, enm := range iface.Enums {
			enmName := ToPascalCase(enm.Name)
			sb.WriteString(fmt.Sprintf("type %s int\n\nconst (\n", enmName))
			for i, c := range enm.Cases {
				if i == 0 {
					sb.WriteString(fmt.Sprintf("\t%s_%s %s = iota\n", enmName, ToPascalCase(c.Name), enmName))
				} else {
					sb.WriteString(fmt.Sprintf("\t%s_%s\n", enmName, ToPascalCase(c.Name)))
				}
			}
			sb.WriteString(")\n\n")
		}

		// 3. Type aliases
		for _, tdef := range iface.TypeDefs {
			sb.WriteString(fmt.Sprintf("type %s = %s\n\n", ToPascalCase(tdef.Name), MapWitTypeToGo(tdef.Type)))
		}

		// 4. Interface declaration
		sb.WriteString(fmt.Sprintf("type %s interface {\n", ToPascalCase(iface.Name)))
		for _, fn := range iface.Functions {
			var params []string
			for _, p := range fn.Params {
				params = append(params, fmt.Sprintf("%s %s", ToCamelCase(p.Name), MapWitTypeToGo(p.Type)))
			}
			retType := MapWitTypeToGo(fn.Results)
			retClause := ""
			if retType != "" {
				if strings.HasPrefix(retType, "(") {
					retClause = " " + retType
				} else {
					retClause = " " + retType
				}
			}
			sb.WriteString(fmt.Sprintf("\t%s(%s)%s\n", ToPascalCase(fn.Name), strings.Join(params, ", "), retClause))
		}
		sb.WriteString("}\n\n")
	}

	return sb.String()
}
