package generate

import (
	"fmt"
	"strings"
	"tools/please_wit/ast"
)

// KotlinGenerator generates idiomatic Kotlin interfaces and models from WIT AST.
type KotlinGenerator struct{}

func (g *KotlinGenerator) Name() string {
	return "kotlin"
}

func (g *KotlinGenerator) mapPrimitiveType(name string) string {
	switch name {
	case "s8":
		return "Byte"
	case "s16":
		return "Short"
	case "s32":
		return "Int"
	case "u8":
		return "Int"
	case "u16":
		return "Int"
	case "u32":
		return "Int"
	case "s64":
		return "Long"
	case "u64":
		return "Long"
	case "f32":
		return "Float"
	case "f64":
		return "Double"
	case "bool":
		return "Boolean"
	case "string":
		return "String"
	case "char":
		return "Char"
	case "unit", "_":
		return "Unit"
	}
	return ToPascalCase(name)
}

// MapWitType converts an AST TypeRef into its idiomatic Kotlin representation.
func (g *KotlinGenerator) MapWitType(t *ast.TypeRef) string {
	if t == nil {
		return "Unit"
	}

	switch t.Kind {
	case ast.KindPrimitive:
		return g.mapPrimitiveType(t.Name)

	case ast.KindList:
		inner := "Any"
		if len(t.TypeArgs) > 0 {
			inner = g.MapWitType(t.TypeArgs[0])
		}
		return fmt.Sprintf("List<%s>", inner)

	case ast.KindOption:
		inner := "Any"
		if len(t.TypeArgs) > 0 {
			inner = g.MapWitType(t.TypeArgs[0])
		}
		return inner + "?"

	case ast.KindResult:
		if len(t.TypeArgs) > 0 {
			okType := g.MapWitType(t.TypeArgs[0])
			if okType == "Unit" {
				return "Unit"
			}
			return okType + "?"
		}
		return "Unit"

	case ast.KindTuple:
		if len(t.TypeArgs) == 2 {
			return fmt.Sprintf("Pair<%s, %s>", g.MapWitType(t.TypeArgs[0]), g.MapWitType(t.TypeArgs[1]))
		} else if len(t.TypeArgs) == 3 {
			return fmt.Sprintf("Triple<%s, %s, %s>", g.MapWitType(t.TypeArgs[0]), g.MapWitType(t.TypeArgs[1]), g.MapWitType(t.TypeArgs[2]))
		}
		return "List<Any>"

	case ast.KindNamed:
		return ToPascalCase(t.Name)
	}

	return "Any"
}

func (g *KotlinGenerator) Generate(pkg *ast.Package, opts Options, baseName string) ([]OutputFile, error) {
	filename := opts.CompanionFilename
	if filename == "" {
		if pascalName := ToPascalCase(baseName); pascalName != "" {
			filename = pascalName + ".kt"
		} else {
			filename = "WitBindings.kt"
		}
	} else if !strings.HasSuffix(filename, ".kt") {
		filename += ".kt"
	}

	content := g.generateKotlinCode(pkg, opts.Package)
	return []OutputFile{{Name: filename, Content: content}}, nil
}

func (g *KotlinGenerator) resolvePackage(pkg *ast.Package, targetPackage string) string {
	resolved := targetPackage
	if resolved == "" {
		if pkg.Namespace != "" && pkg.Name != "" {
			resolved = fmt.Sprintf("%s.%s", pkg.Namespace, pkg.Name)
		} else if pkg.Name != "" {
			resolved = pkg.Name
		} else {
			resolved = "wit.bindings"
		}
	}
	return strings.ReplaceAll(resolved, ":", ".")
}

func (g *KotlinGenerator) processRecords(sb *strings.Builder, records []ast.Record) {
	for _, rec := range records {
		sb.WriteString(fmt.Sprintf("public data class %s(\n", ToPascalCase(rec.Name)))
		for i, field := range rec.Fields {
			comma := ","
			if i == len(rec.Fields)-1 {
				comma = ""
			}
			sb.WriteString(fmt.Sprintf("    val %s: %s%s\n", ToCamelCase(field.Name), g.MapWitType(field.Type), comma))
		}
		sb.WriteString(")\n\n")
	}
}

func (g *KotlinGenerator) processEnums(sb *strings.Builder, enums []ast.Enum) {
	for _, enm := range enums {
		sb.WriteString(fmt.Sprintf("public enum class %s {\n", ToPascalCase(enm.Name)))
		var cases []string
		for _, c := range enm.Cases {
			cases = append(cases, fmt.Sprintf("    %s", strings.ToUpper(ToSnakeCase(c.Name))))
		}
		sb.WriteString(strings.Join(cases, ",\n"))
		sb.WriteString(";\n}\n\n")
	}
}

func (g *KotlinGenerator) processTypeAliases(sb *strings.Builder, typeDefs []ast.TypeDef) {
	for _, tdef := range typeDefs {
		sb.WriteString(fmt.Sprintf("public typealias %s = %s\n\n", ToPascalCase(tdef.Name), g.MapWitType(tdef.Type)))
	}
}

func (g *KotlinGenerator) processInterface(sb *strings.Builder, iface ast.Interface) {
	sb.WriteString(fmt.Sprintf("public interface %s {\n", ToPascalCase(iface.Name)))
	for _, fn := range iface.Functions {
		var params []string
		for _, p := range fn.Params {
			params = append(params, fmt.Sprintf("%s: %s", ToCamelCase(p.Name), g.MapWitType(p.Type)))
		}
		retType := g.MapWitType(fn.Results)
		retClause := ""
		if retType != "Unit" {
			retClause = ": " + retType
		}
		sb.WriteString(fmt.Sprintf("    fun %s(%s)%s\n", ToCamelCase(fn.Name), strings.Join(params, ", "), retClause))
	}
	sb.WriteString("}\n\n")
}

func (g *KotlinGenerator) generateKotlinCode(pkg *ast.Package, targetPackage string) string {
	var sb strings.Builder
	sb.WriteString("// Auto-generated by please_wit from WIT AST. DO NOT EDIT.\n")

	resolvedPkg := g.resolvePackage(pkg, targetPackage)
	sb.WriteString(fmt.Sprintf("package %s\n\n", resolvedPkg))

	for _, iface := range pkg.Interfaces {
		// 1. Records
		g.processRecords(&sb, iface.Records)

		// 2. Enums
		g.processEnums(&sb, iface.Enums)

		// 3. Type aliases
		g.processTypeAliases(&sb, iface.TypeDefs)

		// 4. Interface declaration
		g.processInterface(&sb, iface)
	}

	return sb.String()
}
