package generate

import (
	"testing"
	"tools/please_wit/ast"
)

func TestPythonGenerator_MapWitType(t *testing.T) {
	gen := &PythonGenerator{}

	tests := []struct {
		name    string
		typeRef *ast.TypeRef
		want    string
	}{
		{name: "nil", typeRef: nil, want: "None"},
		{name: "s8", typeRef: &ast.TypeRef{Kind: ast.KindPrimitive, Name: "s8"}, want: "int"},
		{name: "s16", typeRef: &ast.TypeRef{Kind: ast.KindPrimitive, Name: "s16"}, want: "int"},
		{name: "s32", typeRef: &ast.TypeRef{Kind: ast.KindPrimitive, Name: "s32"}, want: "int"},
		{name: "s64", typeRef: &ast.TypeRef{Kind: ast.KindPrimitive, Name: "s64"}, want: "int"},
		{name: "u8", typeRef: &ast.TypeRef{Kind: ast.KindPrimitive, Name: "u8"}, want: "int"},
		{name: "u16", typeRef: &ast.TypeRef{Kind: ast.KindPrimitive, Name: "u16"}, want: "int"},
		{name: "u32", typeRef: &ast.TypeRef{Kind: ast.KindPrimitive, Name: "u32"}, want: "int"},
		{name: "u64", typeRef: &ast.TypeRef{Kind: ast.KindPrimitive, Name: "u64"}, want: "int"},
		{name: "f32", typeRef: &ast.TypeRef{Kind: ast.KindPrimitive, Name: "f32"}, want: "float"},
		{name: "f64", typeRef: &ast.TypeRef{Kind: ast.KindPrimitive, Name: "f64"}, want: "float"},
		{name: "bool", typeRef: &ast.TypeRef{Kind: ast.KindPrimitive, Name: "bool"}, want: "bool"},
		{name: "string", typeRef: &ast.TypeRef{Kind: ast.KindPrimitive, Name: "string"}, want: "str"},
		{name: "char", typeRef: &ast.TypeRef{Kind: ast.KindPrimitive, Name: "char"}, want: "str"},
		{name: "unit", typeRef: &ast.TypeRef{Kind: ast.KindPrimitive, Name: "unit"}, want: "None"},
		{name: "underscore", typeRef: &ast.TypeRef{Kind: ast.KindPrimitive, Name: "_"}, want: "None"},
		{name: "list of s32", typeRef: &ast.TypeRef{Kind: ast.KindList, TypeArgs: []*ast.TypeRef{{Kind: ast.KindPrimitive, Name: "s32"}}}, want: "List[int]"},
		{name: "empty list", typeRef: &ast.TypeRef{Kind: ast.KindList}, want: "List[Any]"},
		{name: "option of string", typeRef: &ast.TypeRef{Kind: ast.KindOption, TypeArgs: []*ast.TypeRef{{Kind: ast.KindPrimitive, Name: "string"}}}, want: "Optional[str]"},
		{name: "empty option", typeRef: &ast.TypeRef{Kind: ast.KindOption}, want: "Optional[Any]"},
		{name: "result of s32", typeRef: &ast.TypeRef{Kind: ast.KindResult, TypeArgs: []*ast.TypeRef{{Kind: ast.KindPrimitive, Name: "s32"}}}, want: "Optional[int]"},
		{name: "result of unit", typeRef: &ast.TypeRef{Kind: ast.KindResult, TypeArgs: []*ast.TypeRef{{Kind: ast.KindPrimitive, Name: "unit"}}}, want: "None"},
		{name: "empty result", typeRef: &ast.TypeRef{Kind: ast.KindResult}, want: "None"},
		{name: "tuple of s32 and string", typeRef: &ast.TypeRef{Kind: ast.KindTuple, TypeArgs: []*ast.TypeRef{{Kind: ast.KindPrimitive, Name: "s32"}, {Kind: ast.KindPrimitive, Name: "string"}}}, want: "Tuple[int, str]"},
		{name: "named type", typeRef: &ast.TypeRef{Kind: ast.KindNamed, Name: "my-point"}, want: "MyPoint"},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := gen.MapWitType(tc.typeRef)
			if got != tc.want {
				t.Errorf("name: %s, want: %q, got: %q", tc.name, tc.want, got)
			}
		})
	}
}

func TestPythonGeneratorDirect(t *testing.T) {
	gen := &PythonGenerator{}

	t.Run("generator name", func(t *testing.T) {
		want := "python"
		got := gen.Name()
		if got != want {
			t.Errorf("name: generator name, want: %q, got: %q", want, got)
		}
	})

	tests := []struct {
		name        string
		pkg         *ast.Package
		opts        Options
		baseName    string
		wantContent string
	}{
		{
			name: "basic interface with params and return",
			pkg: &ast.Package{
				Namespace: "demo",
				Name:      "api",
				Interfaces: []ast.Interface{
					{
						Name: "greeter",
						Functions: []ast.Function{
							{
								Name: "say-hello",
								Params: []ast.Param{
									{Name: "name", Type: &ast.TypeRef{Kind: ast.KindPrimitive, Name: "string"}},
								},
								Results: &ast.TypeRef{Kind: ast.KindPrimitive, Name: "string"},
							},
						},
					},
				},
			},
			opts:     Options{},
			baseName: "api",
			wantContent: `# Auto-generated by please_wit from WIT AST. DO NOT EDIT.
from typing import Any, List, Optional, Protocol, Tuple
from dataclasses import dataclass
from enum import Enum

class Greeter(Protocol):
    def say_hello(self, name: str) -> str:
        ...

__all__ = ["Greeter"]
`,
		},
		{
			name: "records, enums, and type aliases",
			pkg: &ast.Package{
				Name: "types",
				Interfaces: []ast.Interface{
					{
						Name: "data-service",
						Records: []ast.Record{
							{
								Name: "user",
								Fields: []ast.Field{
									{Name: "id", Type: &ast.TypeRef{Kind: ast.KindPrimitive, Name: "s64"}},
									{Name: "name", Type: &ast.TypeRef{Kind: ast.KindPrimitive, Name: "string"}},
								},
							},
						},
						Enums: []ast.Enum{
							{
								Name:  "status",
								Cases: []ast.EnumCase{{Name: "active"}, {Name: "inactive"}},
							},
						},
					},
				},
			},
			opts:     Options{},
			baseName: "types",
			wantContent: `# Auto-generated by please_wit from WIT AST. DO NOT EDIT.
from typing import Any, List, Optional, Protocol, Tuple
from dataclasses import dataclass
from enum import Enum

@dataclass
class User:
    id: int
    name: str

class Status(Enum):
    ACTIVE = "active"
    INACTIVE = "inactive"

class DataService(Protocol):
    pass

__all__ = ["DataService", "User", "Status"]
`,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			files, err := gen.Generate(tc.pkg, tc.opts, tc.baseName)
			if err != nil {
				t.Fatalf("Generate failed: %v", err)
			}
			if len(files) != 2 {
				t.Fatalf("expected 2 files (__init__.py and __init__.pyi), got %d", len(files))
			}
			if files[0].Name != "__init__.py" {
				t.Errorf("name: %s, want filename __init__.py, got %s", tc.name, files[0].Name)
			}
			if files[1].Name != "__init__.pyi" {
				t.Errorf("name: %s, want filename __init__.pyi, got %s", tc.name, files[1].Name)
			}
			if files[0].Content != tc.wantContent {
				t.Errorf("name: %s (__init__.py), want: %q, got: %q", tc.name, tc.wantContent, files[0].Content)
			}
			if files[1].Content != tc.wantContent {
				t.Errorf("name: %s (__init__.pyi), want: %q, got: %q", tc.name, tc.wantContent, files[1].Content)
			}
		})
	}
}
