package generate

import (
	"fmt"
	"strings"
	"tools/please_wit/ast"
)

// MapWitTypeToPython converts an AST TypeRef into its Python typing representation.
func MapWitTypeToPython(t *ast.TypeRef) string {
	if t == nil {
		return "None"
	}

	switch t.Kind {
	case ast.KindPrimitive:
		switch t.Name {
		case "s8", "s16", "s32", "s64", "u8", "u16", "u32", "u64":
			return "int"
		case "f32", "f64":
			return "float"
		case "bool":
			return "bool"
		case "string", "char":
			return "str"
		case "unit", "_":
			return "None"
		}
		return ToPascalCase(t.Name)

	case ast.KindList:
		inner := "Any"
		if len(t.TypeArgs) > 0 {
			inner = MapWitTypeToPython(t.TypeArgs[0])
		}
		return fmt.Sprintf("List[%s]", inner)

	case ast.KindOption:
		inner := "Any"
		if len(t.TypeArgs) > 0 {
			inner = MapWitTypeToPython(t.TypeArgs[0])
		}
		return fmt.Sprintf("Optional[%s]", inner)

	case ast.KindResult:
		if len(t.TypeArgs) > 0 {
			okType := MapWitTypeToPython(t.TypeArgs[0])
			if okType == "None" {
				return "None"
			}
			return fmt.Sprintf("Optional[%s]", okType)
		}
		return "None"

	case ast.KindTuple:
		var parts []string
		for _, arg := range t.TypeArgs {
			parts = append(parts, MapWitTypeToPython(arg))
		}
		return fmt.Sprintf("Tuple[%s]", strings.Join(parts, ", "))

	case ast.KindNamed:
		return ToPascalCase(t.Name)
	}

	return "Any"
}

// GeneratePythonCode emits Python protocol definitions and type stubs from a WIT package AST.
func GeneratePythonCode(pkg *ast.Package) (pyCode, pyiCode string) {
	var sb strings.Builder
	sb.WriteString("# Auto-generated by please_wit from WIT AST. DO NOT EDIT.\n")
	sb.WriteString("from typing import Any, List, Optional, Protocol, Tuple\n")
	sb.WriteString("from dataclasses import dataclass\n")
	sb.WriteString("from enum import Enum\n\n")

	var exportedNames []string

	for _, iface := range pkg.Interfaces {
		ifaceName := ToPascalCase(iface.Name)
		exportedNames = append(exportedNames, ifaceName)

		// 1. Records
		for _, rec := range iface.Records {
			recName := ToPascalCase(rec.Name)
			exportedNames = append(exportedNames, recName)
			sb.WriteString("@dataclass\n")
			sb.WriteString(fmt.Sprintf("class %s:\n", recName))
			if len(rec.Fields) == 0 {
				sb.WriteString("    pass\n\n")
			} else {
				for _, f := range rec.Fields {
					sb.WriteString(fmt.Sprintf("    %s: %s\n", ToSnakeCase(f.Name), MapWitTypeToPython(f.Type)))
				}
				sb.WriteString("\n")
			}
		}

		// 2. Enums
		for _, enm := range iface.Enums {
			enmName := ToPascalCase(enm.Name)
			exportedNames = append(exportedNames, enmName)
			sb.WriteString(fmt.Sprintf("class %s(Enum):\n", enmName))
			if len(enm.Cases) == 0 {
				sb.WriteString("    pass\n\n")
			} else {
				for _, c := range enm.Cases {
					sb.WriteString(fmt.Sprintf("    %s = %q\n", strings.ToUpper(ToSnakeCase(c.Name)), c.Name))
				}
				sb.WriteString("\n")
			}
		}

		// 3. Protocol
		sb.WriteString(fmt.Sprintf("class %s(Protocol):\n", ifaceName))
		if len(iface.Functions) == 0 {
			sb.WriteString("    pass\n\n")
		} else {
			for _, fn := range iface.Functions {
				var params []string
				params = append(params, "self")
				for _, p := range fn.Params {
					params = append(params, fmt.Sprintf("%s: %s", ToSnakeCase(p.Name), MapWitTypeToPython(p.Type)))
				}
				retType := MapWitTypeToPython(fn.Results)
				sb.WriteString(fmt.Sprintf("    def %s(%s) -> %s:\n        ...\n\n", ToSnakeCase(fn.Name), strings.Join(params, ", "), retType))
			}
		}
	}

	var allList []string
	for _, name := range exportedNames {
		allList = append(allList, fmt.Sprintf("%q", name))
	}
	sb.WriteString(fmt.Sprintf("__all__ = [%s]\n", strings.Join(allList, ", ")))

	full := sb.String()
	return full, full
}
