package generate

import (
	"fmt"
	"strings"
	"tools/please_wit/ast"
)

// PythonGenerator generates Python protocols, dataclasses, enums, and .pyi stubs from WIT AST.
type PythonGenerator struct{}

func (g *PythonGenerator) Name() string {
	return "python"
}

func (g *PythonGenerator) mapPrimitiveType(name string) string {
	switch name {
	case "s8", "s16", "s32", "s64", "u8", "u16", "u32", "u64":
		return "int"
	case "f32", "f64":
		return "float"
	case "bool":
		return "bool"
	case "string", "char":
		return "str"
	case "unit", "_":
		return "None"
	}
	return ToPascalCase(name)
}

// MapWitType converts an AST TypeRef into its Python typing representation.
func (g *PythonGenerator) MapWitType(t *ast.TypeRef) string {
	if t == nil {
		return "None"
	}

	switch t.Kind {
	case ast.KindPrimitive:
		return g.mapPrimitiveType(t.Name)

	case ast.KindList:
		inner := "Any"
		if len(t.TypeArgs) > 0 {
			inner = g.MapWitType(t.TypeArgs[0])
		}
		return fmt.Sprintf("List[%s]", inner)

	case ast.KindOption:
		inner := "Any"
		if len(t.TypeArgs) > 0 {
			inner = g.MapWitType(t.TypeArgs[0])
		}
		return fmt.Sprintf("Optional[%s]", inner)

	case ast.KindResult:
		if len(t.TypeArgs) > 0 {
			okType := g.MapWitType(t.TypeArgs[0])
			if okType == "None" {
				return "None"
			}
			return fmt.Sprintf("Optional[%s]", okType)
		}
		return "None"

	case ast.KindTuple:
		var parts []string
		for _, arg := range t.TypeArgs {
			parts = append(parts, g.MapWitType(arg))
		}
		return fmt.Sprintf("Tuple[%s]", strings.Join(parts, ", "))

	case ast.KindNamed:
		return ToPascalCase(t.Name)
	}

	return "Any"
}

func (g *PythonGenerator) Generate(pkg *ast.Package, opts Options, baseName string) ([]OutputFile, error) {
	pyCode, pyiCode := g.generatePythonCode(pkg)
	return []OutputFile{
		{Name: "__init__.py", Content: pyCode},
		{Name: "__init__.pyi", Content: pyiCode},
	}, nil
}

func (g *PythonGenerator) writeHeader(sb *strings.Builder) {
	sb.WriteString("# Auto-generated by please_wit from WIT AST. DO NOT EDIT.\n")
	sb.WriteString("from typing import Any, List, Optional, Protocol, Tuple\n")
	sb.WriteString("from dataclasses import dataclass\n")
	sb.WriteString("from enum import Enum\n\n")
}

func (g *PythonGenerator) processRecords(sb *strings.Builder, records []ast.Record, exportedNames *[]string) {
	for _, rec := range records {
		recName := ToPascalCase(rec.Name)
		*exportedNames = append(*exportedNames, recName)
		sb.WriteString("@dataclass\n")
		sb.WriteString(fmt.Sprintf("class %s:\n", recName))
		if len(rec.Fields) == 0 {
			sb.WriteString("    pass\n\n")
		} else {
			for _, f := range rec.Fields {
				sb.WriteString(fmt.Sprintf("    %s: %s\n", ToSnakeCase(f.Name), g.MapWitType(f.Type)))
			}
			sb.WriteString("\n")
		}
	}
}

func (g *PythonGenerator) processEnums(sb *strings.Builder, enums []ast.Enum, exportedNames *[]string) {
	for _, enm := range enums {
		enmName := ToPascalCase(enm.Name)
		*exportedNames = append(*exportedNames, enmName)
		sb.WriteString(fmt.Sprintf("class %s(Enum):\n", enmName))
		if len(enm.Cases) == 0 {
			sb.WriteString("    pass\n\n")
		} else {
			for _, c := range enm.Cases {
				sb.WriteString(fmt.Sprintf("    %s = %q\n", strings.ToUpper(ToSnakeCase(c.Name)), c.Name))
			}
			sb.WriteString("\n")
		}
	}
}

func (g *PythonGenerator) processProtocol(sb *strings.Builder, iface ast.Interface, exportedNames *[]string) {
	ifaceName := ToPascalCase(iface.Name)
	sb.WriteString(fmt.Sprintf("class %s(Protocol):\n", ifaceName))
	if len(iface.Functions) == 0 {
		sb.WriteString("    pass\n\n")
	} else {
		for _, fn := range iface.Functions {
			var params []string
			params = append(params, "self")
			for _, p := range fn.Params {
				params = append(params, fmt.Sprintf("%s: %s", ToSnakeCase(p.Name), g.MapWitType(p.Type)))
			}
			retType := g.MapWitType(fn.Results)
			sb.WriteString(fmt.Sprintf("    def %s(%s) -> %s:\n        ...\n\n", ToSnakeCase(fn.Name), strings.Join(params, ", "), retType))
		}
	}
}

func (g *PythonGenerator) processResources(sb *strings.Builder, resources []ast.Resource, exportedNames *[]string) {
	for _, res := range resources {
		resName := ToPascalCase(res.Name)
		*exportedNames = append(*exportedNames, resName)
		sb.WriteString(fmt.Sprintf("class %s(Protocol):\n", resName))
		if len(res.Methods) == 0 {
			sb.WriteString("    pass\n\n")
		} else {
			for _, fn := range res.Methods {
				var params []string
				params = append(params, "self")
				for _, p := range fn.Params {
					params = append(params, fmt.Sprintf("%s: %s", ToSnakeCase(p.Name), g.MapWitType(p.Type)))
				}
				retType := g.MapWitType(fn.Results)
				sb.WriteString(fmt.Sprintf("    def %s(%s) -> %s:\n        ...\n\n", ToSnakeCase(fn.Name), strings.Join(params, ", "), retType))
			}
		}
	}
}

func (g *PythonGenerator) generatePythonCode(pkg *ast.Package) (pyCode, pyiCode string) {
	var sb strings.Builder
	g.writeHeader(&sb)

	var exportedNames []string

	for _, iface := range pkg.Interfaces {
		ifaceName := ToPascalCase(iface.Name)

		hasResourceWithSameName := false
		for _, res := range iface.Resources {
			if ToPascalCase(res.Name) == ifaceName {
				hasResourceWithSameName = true
				break
			}
		}

		if !hasResourceWithSameName || len(iface.Functions) > 0 {
			exportedNames = append(exportedNames, ifaceName)
		}

		// 1. Records
		g.processRecords(&sb, iface.Records, &exportedNames)

		// 2. Enums
		g.processEnums(&sb, iface.Enums, &exportedNames)

		// 3. Resources
		g.processResources(&sb, iface.Resources, &exportedNames)

		// 4. Protocol
		if !hasResourceWithSameName || len(iface.Functions) > 0 {
			g.processProtocol(&sb, iface, &exportedNames)
		}
	}

	var allList []string
	for _, name := range exportedNames {
		allList = append(allList, fmt.Sprintf("%q", name))
	}
	sb.WriteString(fmt.Sprintf("__all__ = [%s]\n", strings.Join(allList, ", ")))

	full := sb.String()
	return full, full
}
