package generate

import (
	"fmt"
	"strings"
	"tools/please_wit/ast"
)

// MapWitTypeToRust converts an AST TypeRef into its idiomatic Rust representation.
func MapWitTypeToRust(t *ast.TypeRef) string {
	if t == nil {
		return "()"
	}

	switch t.Kind {
	case ast.KindPrimitive:
		switch t.Name {
		case "s8":
			return "i8"
		case "s16":
			return "i16"
		case "s32":
			return "i32"
		case "s64":
			return "i64"
		case "u8":
			return "u8"
		case "u16":
			return "u16"
		case "u32":
			return "u32"
		case "u64":
			return "u64"
		case "f32":
			return "f32"
		case "f64":
			return "f64"
		case "bool":
			return "bool"
		case "string":
			return "String"
		case "char":
			return "char"
		case "unit", "_":
			return "()"
		}
		return ToPascalCase(t.Name)

	case ast.KindList:
		inner := "()"
		if len(t.TypeArgs) > 0 {
			inner = MapWitTypeToRust(t.TypeArgs[0])
		}
		return fmt.Sprintf("Vec<%s>", inner)

	case ast.KindOption:
		inner := "()"
		if len(t.TypeArgs) > 0 {
			inner = MapWitTypeToRust(t.TypeArgs[0])
		}
		return fmt.Sprintf("Option<%s>", inner)

	case ast.KindResult:
		if len(t.TypeArgs) == 2 {
			return fmt.Sprintf("Result<%s, %s>", MapWitTypeToRust(t.TypeArgs[0]), MapWitTypeToRust(t.TypeArgs[1]))
		} else if len(t.TypeArgs) == 1 {
			return fmt.Sprintf("Result<%s, ()>", MapWitTypeToRust(t.TypeArgs[0]))
		}
		return "Result<(), ()>"

	case ast.KindTuple:
		var parts []string
		for _, arg := range t.TypeArgs {
			parts = append(parts, MapWitTypeToRust(arg))
		}
		return fmt.Sprintf("(%s)", strings.Join(parts, ", "))

	case ast.KindNamed:
		return ToPascalCase(t.Name)
	}

	return "()"
}

// GenerateRustCode emits Rust traits and structs from a WIT package AST.
func GenerateRustCode(pkg *ast.Package) string {
	var sb strings.Builder
	sb.WriteString("// Auto-generated by please_wit from WIT AST. DO NOT EDIT.\n\n")

	for _, iface := range pkg.Interfaces {
		// 1. Records
		for _, rec := range iface.Records {
			sb.WriteString("#[derive(Debug, Clone, PartialEq)]\n")
			sb.WriteString(fmt.Sprintf("pub struct %s {\n", ToPascalCase(rec.Name)))
			for _, f := range rec.Fields {
				sb.WriteString(fmt.Sprintf("    pub %s: %s,\n", ToSnakeCase(f.Name), MapWitTypeToRust(f.Type)))
			}
			sb.WriteString("}\n\n")
		}

		// 2. Enums
		for _, enm := range iface.Enums {
			sb.WriteString("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n")
			sb.WriteString(fmt.Sprintf("pub enum %s {\n", ToPascalCase(enm.Name)))
			for _, c := range enm.Cases {
				sb.WriteString(fmt.Sprintf("    %s,\n", ToPascalCase(c.Name)))
			}
			sb.WriteString("}\n\n")
		}

		// 3. Type aliases
		for _, tdef := range iface.TypeDefs {
			sb.WriteString(fmt.Sprintf("pub type %s = %s;\n\n", ToPascalCase(tdef.Name), MapWitTypeToRust(tdef.Type)))
		}

		// 4. Trait declaration
		sb.WriteString(fmt.Sprintf("pub trait %s {\n", ToPascalCase(iface.Name)))
		for _, fn := range iface.Functions {
			var params []string
			params = append(params, "&mut self")
			for _, p := range fn.Params {
				params = append(params, fmt.Sprintf("%s: %s", ToSnakeCase(p.Name), MapWitTypeToRust(p.Type)))
			}
			retType := MapWitTypeToRust(fn.Results)
			retClause := ""
			if retType != "()" {
				retClause = " -> " + retType
			}
			sb.WriteString(fmt.Sprintf("    fn %s(%s)%s;\n", ToSnakeCase(fn.Name), strings.Join(params, ", "), retClause))
		}
		sb.WriteString("}\n\n")
	}

	return sb.String()
}
