package generate

import (
	"fmt"
	"strings"
	"tools/please_wit/ast"
)

// RustGenerator generates Rust traits, structs, and enums from WIT AST.
type RustGenerator struct{}

func (g *RustGenerator) Name() string {
	return "rust"
}

func (g *RustGenerator) mapPrimitiveType(name string) string {
	switch name {
	case "s8":
		return "i8"
	case "s16":
		return "i16"
	case "s32":
		return "i32"
	case "s64":
		return "i64"
	case "u8":
		return "u8"
	case "u16":
		return "u16"
	case "u32":
		return "u32"
	case "u64":
		return "u64"
	case "f32":
		return "f32"
	case "f64":
		return "f64"
	case "bool":
		return "bool"
	case "string":
		return "String"
	case "char":
		return "char"
	case "unit", "_":
		return "()"
	}
	return ToPascalCase(name)
}

// MapWitType converts an AST TypeRef into its idiomatic Rust representation.
func (g *RustGenerator) MapWitType(t *ast.TypeRef) string {
	if t == nil {
		return "()"
	}

	switch t.Kind {
	case ast.KindPrimitive:
		return g.mapPrimitiveType(t.Name)

	case ast.KindList:
		inner := "()"
		if len(t.TypeArgs) > 0 {
			inner = g.MapWitType(t.TypeArgs[0])
		}
		return fmt.Sprintf("Vec<%s>", inner)

	case ast.KindOption:
		inner := "()"
		if len(t.TypeArgs) > 0 {
			inner = g.MapWitType(t.TypeArgs[0])
		}
		return fmt.Sprintf("Option<%s>", inner)

	case ast.KindResult:
		if len(t.TypeArgs) == 2 {
			return fmt.Sprintf("Result<%s, %s>", g.MapWitType(t.TypeArgs[0]), g.MapWitType(t.TypeArgs[1]))
		} else if len(t.TypeArgs) == 1 {
			return fmt.Sprintf("Result<%s, ()>", g.MapWitType(t.TypeArgs[0]))
		}
		return "Result<(), ()>"

	case ast.KindTuple:
		var parts []string
		for _, arg := range t.TypeArgs {
			parts = append(parts, g.MapWitType(arg))
		}
		return fmt.Sprintf("(%s)", strings.Join(parts, ", "))

	case ast.KindNamed:
		return ToPascalCase(t.Name)
	}

	return "()"
}

func (g *RustGenerator) Generate(pkg *ast.Package, opts Options, baseName string) ([]OutputFile, error) {
	filename := opts.CompanionFilename
	if filename == "" {
		if baseName != "" {
			filename = ToSnakeCase(baseName) + ".rs"
		} else {
			filename = "lib.rs"
		}
	}

	content := g.generateRustCode(pkg)
	return []OutputFile{{Name: filename, Content: content}}, nil
}

func (g *RustGenerator) processRecords(sb *strings.Builder, records []ast.Record) {
	for _, rec := range records {
		sb.WriteString("#[derive(Debug, Clone, PartialEq)]\n")
		sb.WriteString(fmt.Sprintf("pub struct %s {\n", ToPascalCase(rec.Name)))
		for _, f := range rec.Fields {
			sb.WriteString(fmt.Sprintf("    pub %s: %s,\n", ToSnakeCase(f.Name), g.MapWitType(f.Type)))
		}
		sb.WriteString("}\n\n")
	}
}

func (g *RustGenerator) processEnums(sb *strings.Builder, enums []ast.Enum) {
	for _, enm := range enums {
		sb.WriteString("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n")
		sb.WriteString(fmt.Sprintf("pub enum %s {\n", ToPascalCase(enm.Name)))
		for _, c := range enm.Cases {
			sb.WriteString(fmt.Sprintf("    %s,\n", ToPascalCase(c.Name)))
		}
		sb.WriteString("}\n\n")
	}
}

func (g *RustGenerator) processTypeAliases(sb *strings.Builder, typeDefs []ast.TypeDef) {
	for _, tdef := range typeDefs {
		sb.WriteString(fmt.Sprintf("pub type %s = %s;\n\n", ToPascalCase(tdef.Name), g.MapWitType(tdef.Type)))
	}
}

func (g *RustGenerator) processResources(sb *strings.Builder, resources []ast.Resource) {
	for _, res := range resources {
		sb.WriteString(fmt.Sprintf("pub trait %s {\n", ToPascalCase(res.Name)))
		for _, fn := range res.Methods {
			var params []string
			params = append(params, "&mut self")
			for _, p := range fn.Params {
				params = append(params, fmt.Sprintf("%s: %s", ToSnakeCase(p.Name), g.MapWitType(p.Type)))
			}
			retType := g.MapWitType(fn.Results)
			retClause := ""
			if retType != "()" {
				retClause = " -> " + retType
			}
			sb.WriteString(fmt.Sprintf("    fn %s(%s)%s;\n", ToSnakeCase(fn.Name), strings.Join(params, ", "), retClause))
		}
		sb.WriteString("}\n\n")
	}
}

func (g *RustGenerator) processTrait(sb *strings.Builder, iface ast.Interface) {
	sb.WriteString(fmt.Sprintf("pub trait %s {\n", ToPascalCase(iface.Name)))
	for _, fn := range iface.Functions {
		var params []string
		params = append(params, "&mut self")
		for _, p := range fn.Params {
			params = append(params, fmt.Sprintf("%s: %s", ToSnakeCase(p.Name), g.MapWitType(p.Type)))
		}
		retType := g.MapWitType(fn.Results)
		retClause := ""
		if retType != "()" {
			retClause = " -> " + retType
		}
		sb.WriteString(fmt.Sprintf("    fn %s(%s)%s;\n", ToSnakeCase(fn.Name), strings.Join(params, ", "), retClause))
	}
	sb.WriteString("}\n\n")
}

func (g *RustGenerator) generateRustCode(pkg *ast.Package) string {
	var sb strings.Builder
	sb.WriteString("// Auto-generated by please_wit from WIT AST. DO NOT EDIT.\n\n")

	for _, iface := range pkg.Interfaces {
		// 1. Records
		g.processRecords(&sb, iface.Records)

		// 2. Enums
		g.processEnums(&sb, iface.Enums)

		// 3. Type aliases
		g.processTypeAliases(&sb, iface.TypeDefs)

		// 4. Resources
		g.processResources(&sb, iface.Resources)

		// 5. Trait declaration
		hasResourceWithSameName := false
		for _, res := range iface.Resources {
			if ToPascalCase(res.Name) == ToPascalCase(iface.Name) {
				hasResourceWithSameName = true
				break
			}
		}

		if !hasResourceWithSameName || len(iface.Functions) > 0 {
			g.processTrait(&sb, iface)
		}
	}

	return sb.String()
}
