package generate

import (
	"fmt"
	"strings"
	"tools/please_wit/ast"
)

// MapWitTypeToSwift converts an AST TypeRef into its idiomatic Swift representation.
func MapWitTypeToSwift(t *ast.TypeRef) string {
	if t == nil {
		return "Void"
	}

	switch t.Kind {
	case ast.KindPrimitive:
		switch t.Name {
		case "s8":
			return "Int8"
		case "s16":
			return "Int16"
		case "s32":
			return "Int32"
		case "s64":
			return "Int64"
		case "u8":
			return "UInt8"
		case "u16":
			return "UInt16"
		case "u32":
			return "UInt32"
		case "u64":
			return "UInt64"
		case "f32":
			return "Float"
		case "f64":
			return "Double"
		case "bool":
			return "Bool"
		case "string":
			return "String"
		case "char":
			return "Character"
		case "unit", "_":
			return "Void"
		}
		return ToPascalCase(t.Name)

	case ast.KindList:
		inner := "Any"
		if len(t.TypeArgs) > 0 {
			inner = MapWitTypeToSwift(t.TypeArgs[0])
		}
		return fmt.Sprintf("[%s]", inner)

	case ast.KindOption:
		inner := "Any"
		if len(t.TypeArgs) > 0 {
			inner = MapWitTypeToSwift(t.TypeArgs[0])
		}
		return inner + "?"

	case ast.KindResult:
		if len(t.TypeArgs) > 0 {
			okType := MapWitTypeToSwift(t.TypeArgs[0])
			if okType == "Void" {
				return "Void"
			}
			return okType + "?"
		}
		return "Void"

	case ast.KindTuple:
		var parts []string
		for _, arg := range t.TypeArgs {
			parts = append(parts, MapWitTypeToSwift(arg))
		}
		return fmt.Sprintf("(%s)", strings.Join(parts, ", "))

	case ast.KindNamed:
		return ToPascalCase(t.Name)
	}

	return "Any"
}

// GenerateSwiftCode emits Swift protocols and types from a WIT package AST.
func GenerateSwiftCode(pkg *ast.Package) string {
	var sb strings.Builder
	sb.WriteString("// Auto-generated by please_wit from WIT AST. DO NOT EDIT.\n")
	sb.WriteString("import Foundation\n\n")

	for _, iface := range pkg.Interfaces {
		// 1. Records
		for _, rec := range iface.Records {
			sb.WriteString(fmt.Sprintf("public struct %s: Equatable, Codable {\n", ToPascalCase(rec.Name)))
			for _, field := range rec.Fields {
				sb.WriteString(fmt.Sprintf("    public var %s: %s\n", ToCamelCase(field.Name), MapWitTypeToSwift(field.Type)))
			}
			sb.WriteString("}\n\n")
		}

		// 2. Enums
		for _, enm := range iface.Enums {
			sb.WriteString(fmt.Sprintf("public enum %s: String, Codable {\n", ToPascalCase(enm.Name)))
			for _, c := range enm.Cases {
				sb.WriteString(fmt.Sprintf("    case %s\n", ToCamelCase(c.Name)))
			}
			sb.WriteString("}\n\n")
		}

		// 3. Type aliases
		for _, tdef := range iface.TypeDefs {
			sb.WriteString(fmt.Sprintf("public typealias %s = %s\n\n", ToPascalCase(tdef.Name), MapWitTypeToSwift(tdef.Type)))
		}

		// 4. Protocol declaration
		sb.WriteString(fmt.Sprintf("public protocol %s {\n", ToPascalCase(iface.Name)))
		for _, fn := range iface.Functions {
			var params []string
			for _, p := range fn.Params {
				params = append(params, fmt.Sprintf("%s: %s", ToCamelCase(p.Name), MapWitTypeToSwift(p.Type)))
			}
			retType := MapWitTypeToSwift(fn.Results)
			retClause := ""
			if retType != "Void" {
				retClause = " -> " + retType
			}
			sb.WriteString(fmt.Sprintf("    func %s(%s)%s\n", ToCamelCase(fn.Name), strings.Join(params, ", "), retClause))
		}
		sb.WriteString("}\n\n")
	}

	return sb.String()
}
