package generate

import (
	"fmt"
	"strings"
	"tools/please_wit/ast"
)

// SwiftGenerator generates Swift protocols, types, and module maps from WIT AST.
type SwiftGenerator struct{}

func (g *SwiftGenerator) Name() string {
	return "swift"
}

func (g *SwiftGenerator) mapPrimitiveType(name string) string {
	switch name {
	case "s8":
		return "Int8"
	case "s16":
		return "Int16"
	case "s32":
		return "Int32"
	case "s64":
		return "Int64"
	case "u8":
		return "UInt8"
	case "u16":
		return "UInt16"
	case "u32":
		return "UInt32"
	case "u64":
		return "UInt64"
	case "f32":
		return "Float"
	case "f64":
		return "Double"
	case "bool":
		return "Bool"
	case "string":
		return "String"
	case "char":
		return "Character"
	case "unit", "_":
		return "Void"
	}
	return ToPascalCase(name)
}

// MapWitType converts an AST TypeRef into its idiomatic Swift representation.
func (g *SwiftGenerator) MapWitType(t *ast.TypeRef) string {
	if t == nil {
		return "Void"
	}

	switch t.Kind {
	case ast.KindPrimitive:
		return g.mapPrimitiveType(t.Name)

	case ast.KindList:
		inner := "Any"
		if len(t.TypeArgs) > 0 {
			inner = g.MapWitType(t.TypeArgs[0])
		}
		return fmt.Sprintf("[%s]", inner)

	case ast.KindOption:
		inner := "Any"
		if len(t.TypeArgs) > 0 {
			inner = g.MapWitType(t.TypeArgs[0])
		}
		return inner + "?"

	case ast.KindResult:
		if len(t.TypeArgs) > 0 {
			okType := g.MapWitType(t.TypeArgs[0])
			if okType == "Void" {
				return "Void"
			}
			return okType + "?"
		}
		return "Void"

	case ast.KindTuple:
		var parts []string
		for _, arg := range t.TypeArgs {
			parts = append(parts, g.MapWitType(arg))
		}
		return fmt.Sprintf("(%s)", strings.Join(parts, ", "))

	case ast.KindNamed:
		return ToPascalCase(t.Name)
	}

	return "Any"
}

func (g *SwiftGenerator) Generate(pkg *ast.Package, opts Options, baseName string) ([]OutputFile, error) {
	filename := opts.CompanionFilename
	pascalName := ToPascalCase(baseName)
	if filename == "" {
		if pascalName != "" {
			filename = pascalName + ".swift"
		} else {
			filename = "WitBridging.swift"
		}
	} else if !strings.HasSuffix(filename, ".swift") {
		filename += ".swift"
	}

	content := g.generateSwiftCode(pkg)

	modName := opts.ModuleName
	if modName == "" {
		if pascalName != "" {
			modName = pascalName
		} else {
			modName = strings.TrimSuffix(filename, ".swift")
		}
	}
	moduleMap := fmt.Sprintf("module %s {\n    export *\n}\n", modName)

	return []OutputFile{
		{Name: filename, Content: content},
		{Name: "module.modulemap", Content: moduleMap},
	}, nil
}

func (g *SwiftGenerator) processRecords(sb *strings.Builder, records []ast.Record) {
	for _, rec := range records {
		sb.WriteString(fmt.Sprintf("public struct %s: Equatable, Codable {\n", ToPascalCase(rec.Name)))
		for _, field := range rec.Fields {
			sb.WriteString(fmt.Sprintf("    public var %s: %s\n", ToCamelCase(field.Name), g.MapWitType(field.Type)))
		}
		sb.WriteString("}\n\n")
	}
}

func (g *SwiftGenerator) processEnums(sb *strings.Builder, enums []ast.Enum) {
	for _, enm := range enums {
		sb.WriteString(fmt.Sprintf("public enum %s: String, Codable {\n", ToPascalCase(enm.Name)))
		for _, c := range enm.Cases {
			sb.WriteString(fmt.Sprintf("    case %s\n", ToCamelCase(c.Name)))
		}
		sb.WriteString("}\n\n")
	}
}

func (g *SwiftGenerator) processTypeAliases(sb *strings.Builder, typeDefs []ast.TypeDef) {
	for _, tdef := range typeDefs {
		sb.WriteString(fmt.Sprintf("public typealias %s = %s\n\n", ToPascalCase(tdef.Name), g.MapWitType(tdef.Type)))
	}
}

func (g *SwiftGenerator) processResources(sb *strings.Builder, resources []ast.Resource) {
	for _, res := range resources {
		sb.WriteString(fmt.Sprintf("public protocol %s {\n", ToPascalCase(res.Name)))
		for _, fn := range res.Methods {
			var params []string
			for _, p := range fn.Params {
				params = append(params, fmt.Sprintf("%s: %s", ToCamelCase(p.Name), g.MapWitType(p.Type)))
			}
			retType := g.MapWitType(fn.Results)
			retClause := ""
			if retType != "Void" {
				retClause = " -> " + retType
			}
			sb.WriteString(fmt.Sprintf("    func %s(%s)%s\n", ToCamelCase(fn.Name), strings.Join(params, ", "), retClause))
		}
		sb.WriteString("}\n\n")
	}
}

func (g *SwiftGenerator) processProtocol(sb *strings.Builder, iface ast.Interface) {
	sb.WriteString(fmt.Sprintf("public protocol %s {\n", ToPascalCase(iface.Name)))
	for _, fn := range iface.Functions {
		var params []string
		for _, p := range fn.Params {
			params = append(params, fmt.Sprintf("%s: %s", ToCamelCase(p.Name), g.MapWitType(p.Type)))
		}
		retType := g.MapWitType(fn.Results)
		retClause := ""
		if retType != "Void" {
			retClause = " -> " + retType
		}
		sb.WriteString(fmt.Sprintf("    func %s(%s)%s\n", ToCamelCase(fn.Name), strings.Join(params, ", "), retClause))
	}
	sb.WriteString("}\n\n")
}

func (g *SwiftGenerator) generateSwiftCode(pkg *ast.Package) string {
	var sb strings.Builder
	sb.WriteString("// Auto-generated by please_wit from WIT AST. DO NOT EDIT.\n")
	sb.WriteString("import Foundation\n\n")

	for _, iface := range pkg.Interfaces {
		// 1. Records
		g.processRecords(&sb, iface.Records)

		// 2. Enums
		g.processEnums(&sb, iface.Enums)

		// 3. Type aliases
		g.processTypeAliases(&sb, iface.TypeDefs)

		// 4. Resources
		g.processResources(&sb, iface.Resources)

		// 5. Protocol declaration
		hasResourceWithSameName := false
		for _, res := range iface.Resources {
			if ToPascalCase(res.Name) == ToPascalCase(iface.Name) {
				hasResourceWithSameName = true
				break
			}
		}

		if !hasResourceWithSameName || len(iface.Functions) > 0 {
			g.processProtocol(&sb, iface)
		}
	}

	return sb.String()
}
