package generate

import (
	"fmt"
	"strings"
	"tools/please_wit/ast"
)

// TypeScriptGenerator generates TypeScript interface definitions from WIT AST.
type TypeScriptGenerator struct{}

func (g *TypeScriptGenerator) Name() string {
	return "typescript"
}

// MapWitType converts an AST TypeRef into its idiomatic TypeScript representation.
func (g *TypeScriptGenerator) MapWitType(t *ast.TypeRef) string {
	if t == nil {
		return "void"
	}

	switch t.Kind {
	case ast.KindPrimitive:
		switch t.Name {
		case "s8", "s16", "s32", "u8", "u16", "u32", "f32", "f64":
			return "number"
		case "s64", "u64":
			return "bigint"
		case "bool":
			return "boolean"
		case "string", "char":
			return "string"
		case "unit", "_":
			return "void"
		}
		return ToPascalCase(t.Name)

	case ast.KindList:
		inner := "unknown"
		if len(t.TypeArgs) > 0 {
			inner = g.MapWitType(t.TypeArgs[0])
		}
		return fmt.Sprintf("%s[]", inner)

	case ast.KindOption:
		inner := "unknown"
		if len(t.TypeArgs) > 0 {
			inner = g.MapWitType(t.TypeArgs[0])
		}
		return fmt.Sprintf("%s | null", inner)

	case ast.KindResult:
		if len(t.TypeArgs) > 0 {
			okType := g.MapWitType(t.TypeArgs[0])
			if okType == "void" {
				return "void"
			}
			return fmt.Sprintf("%s | null", okType)
		}
		return "void"

	case ast.KindTuple:
		var parts []string
		for _, arg := range t.TypeArgs {
			parts = append(parts, g.MapWitType(arg))
		}
		return fmt.Sprintf("[%s]", strings.Join(parts, ", "))

	case ast.KindNamed:
		return ToPascalCase(t.Name)
	}

	return "unknown"
}

func (g *TypeScriptGenerator) Generate(pkg *ast.Package, opts Options, baseName string) ([]OutputFile, error) {
	filename := opts.CompanionFilename
	if filename == "" {
		if baseName != "" {
			filename = baseName + ".d.ts"
		} else {
			filename = "index.d.ts"
		}
	}

	content := g.generateTSCode(pkg)
	files := []OutputFile{{Name: filename, Content: content}}
	if filename != "index.d.ts" {
		files = append(files, OutputFile{Name: "index.d.ts", Content: content})
	}
	return files, nil
}

func (g *TypeScriptGenerator) generateTSCode(pkg *ast.Package) string {
	var sb strings.Builder
	sb.WriteString("// Auto-generated by please_wit from WIT AST. DO NOT EDIT.\n\n")

	for _, iface := range pkg.Interfaces {
		// 1. Records
		for _, rec := range iface.Records {
			sb.WriteString(fmt.Sprintf("export interface %s {\n", ToPascalCase(rec.Name)))
			for _, field := range rec.Fields {
				sb.WriteString(fmt.Sprintf("  %s: %s;\n", ToCamelCase(field.Name), g.MapWitType(field.Type)))
			}
			sb.WriteString("}\n\n")
		}

		// 2. Enums
		for _, enm := range iface.Enums {
			sb.WriteString(fmt.Sprintf("export enum %s {\n", ToPascalCase(enm.Name)))
			for _, c := range enm.Cases {
				sb.WriteString(fmt.Sprintf("  %s = %q,\n", ToPascalCase(c.Name), c.Name))
			}
			sb.WriteString("}\n\n")
		}

		// 3. Type aliases
		for _, tdef := range iface.TypeDefs {
			sb.WriteString(fmt.Sprintf("export type %s = %s;\n\n", ToPascalCase(tdef.Name), g.MapWitType(tdef.Type)))
		}

		// 4. Interface declaration
		sb.WriteString(fmt.Sprintf("export interface %s {\n", ToPascalCase(iface.Name)))
		for _, fn := range iface.Functions {
			var params []string
			for _, p := range fn.Params {
				params = append(params, fmt.Sprintf("%s: %s", ToCamelCase(p.Name), g.MapWitType(p.Type)))
			}
			retType := g.MapWitType(fn.Results)
			sb.WriteString(fmt.Sprintf("  %s(%s): %s;\n", ToCamelCase(fn.Name), strings.Join(params, ", "), retType))
		}
		sb.WriteString("}\n\n")
	}

	return sb.String()
}
