filegroup(
    name = "constants",
    srcs = ["constants.build_defs"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "kotlin",
    srcs = ["kotlin.build_defs"],
    visibility = ["PUBLIC"],
)
