package bundle

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"tools/please_ts/importmap"
)

// Options holds configuration for bundling JavaScript/TypeScript assets.
type Options struct {
	Deno        string
	BundlerTool string
	Out         string
	Main        string
	Srcs        []string
	Deps        []string
	ModuleName  string
	Format      string // "esm" | "iife"
	Minify      bool
	Sourcemap   bool
	Flags       []string
}

// Run bundles the source files into a single distribution asset.
func Run(opts Options) error {
	if opts.Main == "" {
		return fmt.Errorf("main entry point must be specified for ts_bundle")
	}
	if opts.Out == "" {
		return fmt.Errorf("output bundle path must be specified for ts_bundle")
	}

	if err := os.MkdirAll(filepath.Dir(opts.Out), 0755); err != nil {
		return err
	}

	// 1. If an external bundler tool (e.g. esbuild) is explicitly configured, delegate to it
	if opts.BundlerTool != "" {
		return runExternalBundler(opts)
	}

	// 2. Otherwise, use hermetic built-in bundling
	return runBuiltinBundler(opts)
}

func runExternalBundler(opts Options) error {
	args := []string{opts.Main, "--outfile=" + opts.Out, "--bundle"}
	if opts.Format != "" {
		args = append(args, "--format="+opts.Format)
	}
	if opts.Minify {
		args = append(args, "--minify")
	}
	if opts.Sourcemap {
		args = append(args, "--sourcemap")
	}
	args = append(args, opts.Flags...)

	cmd := exec.Command(opts.BundlerTool, args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func runBuiltinBundler(opts Options) error {
	im, err := importmap.Synthesize(opts.ModuleName, opts.Srcs, opts.Deps, ".")
	if err != nil {
		return fmt.Errorf("failed synthesizing import map: %w", err)
	}

	// Read and resolve entry file
	entryContent, err := os.ReadFile(opts.Main)
	if err != nil {
		return fmt.Errorf("failed reading entry file %s: %w", opts.Main, err)
	}

	// Collect and concatenate imported sources
	var bundleBuilder strings.Builder
	bundleBuilder.WriteString("// Hermetic bundle generated by please_ts\n")

	visited := make(map[string]bool)
	if err := collectBundle(&bundleBuilder, opts.Main, string(entryContent), im, visited); err != nil {
		return fmt.Errorf("bundling failed: %w", err)
	}

	result := bundleBuilder.String()
	if opts.Format == "iife" {
		result = "(function() {\n" + result + "\n})();\n"
	}

	if opts.Minify {
		result = minifyJS(result)
	}

	return os.WriteFile(opts.Out, []byte(result), 0644)
}

func collectBundle(w *strings.Builder, filePath string, content string, im *importmap.ImportMap, visited map[string]bool) error {
	if visited[filePath] {
		return nil
	}
	visited[filePath] = true

	// Match import declarations: import ... from "specifier";
	importRegex := regexp.MustCompile(`(?m)^\s*import\s+(?:(?:[\w*\s{},]+)\s+from\s+)?['"]([^'"]+)['"];?`)
	matches := importRegex.FindAllStringSubmatch(content, -1)

	for _, match := range matches {
		if len(match) > 1 {
			spec := match[1]
			resolvedPath := resolveSpecifier(spec, filePath, im)
			if resolvedPath != "" && !visited[resolvedPath] {
				depContent, err := os.ReadFile(resolvedPath)
				if err == nil {
					if err := collectBundle(w, resolvedPath, string(depContent), im, visited); err != nil {
						return err
					}
				}
			}
		}
	}

	w.WriteString(fmt.Sprintf("\n// Module: %s\n", filePath))
	w.WriteString(content)
	w.WriteString("\n")
	return nil
}

func resolveSpecifier(spec, currentFile string, im *importmap.ImportMap) string {
	if mapped, ok := im.Imports[spec]; ok {
		return strings.TrimPrefix(mapped, "./")
	}

	// Check relative path
	if strings.HasPrefix(spec, "./") || strings.HasPrefix(spec, "../") {
		dir := filepath.Dir(currentFile)
		target := filepath.Join(dir, spec)
		for _, ext := range []string{"", ".ts", ".tsx", ".js", ".mjs"} {
			candidate := target + ext
			if _, err := os.Stat(candidate); err == nil {
				return candidate
			}
		}
	}

	return ""
}

func minifyJS(code string) string {
	// Strip single line comments
	singleComment := regexp.MustCompile(`(?m)//.*$`)
	code = singleComment.ReplaceAllString(code, "")

	// Collapse consecutive whitespaces
	multiWhitespace := regexp.MustCompile(`[ \t]+`)
	code = multiWhitespace.ReplaceAllString(code, " ")

	return strings.TrimSpace(code)
}
