plugin_repo(
    name = "go",
    owner = "please-build",
    plugin = "go-rules",
    revision = "v1.22.0",
)

filegroup(
    name = "rust",
    srcs = ["//build_defs/rust:rust"],
    visibility = ["PUBLIC"],
)
