plugin_repo(
    name = "go",
    owner = "please-build",
    plugin = "go-rules",
    revision = "v1.22.0",
)

filegroup(
    name = "constants",
    srcs = ["//build_defs/swift:constants"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "swift",
    srcs = ["//build_defs/swift"],
    visibility = ["PUBLIC"],
)
