plugin_repo(
    name = "go",
    owner = "please-build",
    plugin = "go-rules",
    revision = "v1.22.0",
)

filegroup(
    name = "constants",
    srcs = ["//build_defs/kotlin:constants"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "kotlin",
    srcs = ["//build_defs/kotlin:kotlin"],
    visibility = ["PUBLIC"],
)
