filegroup(
    name = "constants",
    srcs = ["//build_defs/wit:constants"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "wit",
    srcs = ["//build_defs/wit"],
    visibility = ["PUBLIC"],
)
