filegroup(
    name = "constants",
    srcs = ["//build_defs/rust:constants"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "rust",
    srcs = ["//build_defs/rust:rust"],
    visibility = ["PUBLIC"],
)

