filegroup(
    name = "constants",
    srcs = ["//build_defs/swift:constants"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "swift",
    srcs = ["//build_defs/swift:swift"],
    visibility = ["PUBLIC"],
)
