filegroup(
    name = "constants",
    srcs = ["constants.build_defs"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "rust",
    srcs = [
        "constants.build_defs",
        "rust.build_defs",
    ],
    visibility = ["PUBLIC"],
)

